apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: strokes-ingress
  labels:
    app: strokes
spec:
  defaultBackend:
    service:
      name: strokes-service-api
      port:
        number: 8000