apiVersion: apps/v1
kind: Deployment
metadata:
  name: strokes-deploy-db
  labels:
    app: strokes
spec:
  selector:
    matchLabels:
      app: strokes
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: strokes
    spec:
      containers:
        - image: classerredev/mysql-db-strokes:latest
          name: strokes-db
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: strokes-secret
                  key: ROOT-PASSWORD  
          volumeMounts:
            - name: strokes-storage-db
              mountPath: /var/lib/mysql
      volumes:
        - name: strokes-storage-db
          persistentVolumeClaim:
            claimName: strokes-pvc